DMP-796-Migration-DB
hmcts/darts-shared-infrastructure pull request #74
Opened 2023-08-30 07:54 UTC by scott-robertson1

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-11-14 10:01 UTC, bancey requested changes

2023-11-14 16:20 UTC, scott-robertson1 commented on database.tf
> +  pgsql_delegated_subnet_id = azurerm_subnet.postgres.id
no joy, issue with the delegated subnets ?

2023-11-23 16:47 UTC, bancey commented on database.tf
> +}
Is this required? Doesn't look like its used
```suggestion
```

2023-11-23 16:50 UTC, scott-robertson1 commented on database.tf
> +}
is it not used in the subnet ?

2023-11-23 17:31 UTC, bancey commented on database.tf
> +}
the `rg_name` local is being passed through to the `resource_group_name` parameter on the subnet. Can't see this in use there.

2023-11-24 09:01 UTC, bancey approved these changes

2023-11-24 09:01 UTC, merged